language: ruby
rvm:
  - 2.3.3-p222

install:
  - rvm install 2.3.3p222
  - bundle install

before_script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rails db:test:prepare

script:
  - bundle exec rspec spec


